version: '3.4'

services:
  devopstask:
    image: node:21.2
    restart_policy:
      condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
