version: '3.4'

services:
  devopstask:
    image: devopstask
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: always

